### ISSUE TITLE
x-order not respected when using $ref

### ISSUE THREAD

**Issue by bjarnemagnussen** [oapi-codegen/oapi-codegen#1611]
When using referencing, e.g.:
```
"properties": {
    "$ref": "#/components/schemas/Properties",
    "x-order": 2
},
```

Then the x-order is not respected. Only if it is put on the actual referenced feature `Properties`. 

Is this expected, or should it be possible to override the x-order value of the feature when defined directly after referencing it?

**Comment by paulmach** [comment]
The spec says there should be no properties next to `$ref`. But, in my opinion, extensions are an exception. 

The core technical problem is kin-openapi is not capturing anything next to `$ref`. 

kin-openapi issue with more information https://github.com/getkin/kin-openapi/issues/900
kin-openapi pr to capture extensions next to $ref https://github.com/getkin/kin-openapi/pull/901

After the pr is merge, we can make the relatively small changes here to address this. However, right now I'm blocked on the merge/release of the upstream change.

**Comment by jamietanna** [comment]
Thanks for the work upstream with this @paulmach, this is now fixed on HEAD, and will be released with the next release (no ETA yet)

**Comment by paulmach** [comment]
This issue is not fully fixed, it was a 3 parter.
1. have kin-openapi read in the extensions next to $ref https://github.com/getkin/kin-openapi/pull/901
2. upgrade the kin-openapi version used here https://github.com/oapi-codegen/oapi-codegen/pull/1689
3. make use of those values in this library https://github.com/oapi-codegen/oapi-codegen/pull/1700

part 3 still needs to happen

**Comment by AndrewCopeland** [comment]
I am still experiencing this issue using the latest version `v2.3.0`, I see there is an open pr #1700 and was wondering if this will be merged soon?

**Comment by jamietanna** [comment]
Sorry if meant to come back to this one, will merge (but not release) today
