### ISSUE TITLE
Problems installing v2.2.0

### ISSUE THREAD

**Issue by osttra-j-sernbrant** [oapi-codegen/oapi-codegen#1650]
```
$ docker run --rm -it golang:1.22
root@9d7fd9b46530:/go# go install github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@v2.2.0
go: downloading github.com/oapi-codegen/oapi-codegen/v2 v2.2.0
go: github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@v2.2.0: version constraints conflict:
        github.com/oapi-codegen/oapi-codegen/v2@v2.2.0: parsing go.mod:
        module declares its path as: github.com/deepmap/oapi-codegen/v2
                but was required as: github.com/oapi-codegen/oapi-codegen/v2
```

**Comment by mromaszewicz** [comment]
I guess that the redirect doesn't work quite as expected, and we need to tag it with a new tag, since I committed the go.mod changes. Can you try it with the latest commit and see if it works for you first?

**Comment by mromaszewicz** [comment]
Yeah, we need a new tag. This worked for me: `# go install github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@0f67d9a`

@jamietanna , I'll make a new release, 2.3.0 after I update the readme.

**Comment by osttra-j-sernbrant** [comment]
latest doesnt work but main does. i see that the tagged 2.2.0 version still has deepmap in go.mod

```
$ docker run --rm -it golang:1.22
root@c72b82581b93:/go# go install github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@latest
go: downloading github.com/oapi-codegen/oapi-codegen v1.16.3
go: downloading github.com/oapi-codegen/oapi-codegen/v2 v2.2.0
go: github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@latest: version constraints conflict:
        github.com/oapi-codegen/oapi-codegen/v2@v2.2.0: parsing go.mod:
        module declares its path as: github.com/deepmap/oapi-codegen/v2
                but was required as: github.com/oapi-codegen/oapi-codegen/v2
root@c72b82581b93:/go#
root@c72b82581b93:/go# go install github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@main
go: downloading github.com/oapi-codegen/oapi-codegen v0.0.0-20240412085346-d18224f3b7ca
go: downloading github.com/oapi-codegen/oapi-codegen/v2 v2.2.1-0.20240606151511-0f67d9a354bc
go: downloading gopkg.in/yaml.v2 v2.4.0
go: downloading github.com/getkin/kin-openapi v0.124.0
go: downloading golang.org/x/text v0.15.0
go: downloading golang.org/x/tools v0.21.0
go: downloading github.com/go-openapi/jsonpointer v0.20.2
go: downloading github.com/invopop/yaml v0.2.0
go: downloading github.com/mohae/deepcopy v0.0.0-20170929034955-c48cc78d4826
go: downloading github.com/perimeterx/marshmallow v1.1.5
go: downloading github.com/go-openapi/swag v0.22.8
go: downloading gopkg.in/yaml.v3 v3.0.1
go: downloading golang.org/x/mod v0.17.0
go: downloading github.com/mailru/easyjson v0.7.7
go: downloading github.com/josharian/intern v1.0.0
```

**Comment by mromaszewicz** [comment]
Please use `v2.3.0`. I pushed it and tested that it works.

**Comment by jamietanna** [comment]
OK so it looks like this was probably us updating the README a little earlier than needed, folks still should've been able to install with:

```
% go install github.com/deepmap/oapi-codegen/v2/cmd/oapi-codegen@v2.2.0
# or
% go install github.com/deepmap/oapi-codegen/v2/cmd/oapi-codegen@latest
```

And then when we were ready to ship the next release, it'd be 

```
% go install github.com/oapi-codegen/oapi-codegen/v2/cmd/oapi-codegen@latest
```

The issue here is that there was no tagged release for the `github.com/oapi-codegen/oapi-codegen/` module, so explicitly trying to install that failed.

I've updated what was [meant to be the v2.3.0 release](https://github.com/oapi-codegen/oapi-codegen/milestone/10) to now be v2.4.0

**Comment by stefanmcshane** [comment]
This issue still exists with both latest and 2.4.1

```bash
go install github.com/deepmap/oapi-codegen/v2/cmd/oapi-codegen@v2.4.1
go: github.com/deepmap/oapi-codegen/v2/cmd/oapi-codegen@v2.4.1: version constraints conflict:
        github.com/deepmap/oapi-codegen/v2@v2.4.1: parsing go.mod:
        module declares its path as: github.com/oapi-codegen/oapi-codegen/v2
                but was required as: github.com/deepmap/oapi-codegen/v2
```


go version go1.23.2 darwin/arm64

**Comment by jamietanna** [comment]
@stefanmcshane please note the new module import path is needed in the `go install` - https://github.com/oapi-codegen/oapi-codegen?tab=readme-ov-file#action-required-the-repository-for-this-project-has-changed

**Comment by stefanmcshane** [comment]
I see - this was a caching issue after failing to install the initial version. Thank you.
