### ISSUE TITLE
Invalid character in function name

### ISSUE THREAD

**Issue by eqinox76** [oapi-codegen/oapi-codegen#60]
Hey all,

we have a special openapi definition which contains the following:
```paths:
  /customer:
    post:
      summary: Create New Customer.
      operationId: customer-fn-create
```
This will fail with:
```
$ oapi-codegen -generate types spec.yaml > gen.go
error generating code: error formatting Go code: 158:14: expected type, found '-' (and 3 more errors)
```
As the generated code will be
```
// customer-fn-createJSONBody defines parameters for CustomerFnCreate.
type customer-fn-createJSONBody CustomerRequest
```

What do you think about auto resolving this issue? Just omit invalid characters in the generated names?

Regards,
Carsten

**Comment by weitzj** [comment]
Related to https://github.com/deepmap/oapi-codegen/issues/71

Fixed in https://github.com/deepmap/oapi-codegen/pull/72

**Comment by weitzj** [comment]
@eqinox76  Could you please try again with the new `master`. This should be fixed. Thanks

**Comment by eqinox76** [comment]
Hey @weitzj,
sorry for the late reply and thanks for the fix.
After testing with a8aa52d i still see that issue. Here is a more complete example:
```
$ oapi-codegen openapi/schema.yaml  > openapi/schema.gen.go
error generating code: error formatting Go code: 42:14: expected type, found '-' (and 1 more errors)
$ cat openapi/schema.yaml 
openapi: 3.0.0
info:
  title: example API
  version: "1.0.0"

paths:
  /customer:
    post:      
      summary: Create New Customer. 
      operationId: customer-fn-create
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CustomerRequest'
  
components:
  schemas:
    CustomerRequest:
      type: object
      properties:
        name:
          type: string
```

**Comment by mromaszewicz** [comment]
This has been resolved. The `ToCamelCase` name normalizer (applied to all operationIds at `pkg/codegen/operations.go:638`) treats `-` as a word separator (`pkg/codegen/utils.go:152`), strips it, and capitalizes the next letter.

So the reproduction case `customer-fn-create` becomes `CustomerFnCreate`, and the request body type becomes `CustomerFnCreateJSONRequestBody` — valid Go code.

Closing as completed.
